name: CI

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/verify

  version-bump:
    runs-on: ubuntu-latest
    needs: verify
    if: ${{ github.ref == 'refs/heads/main' }}
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: phips28/gh-action-bump-version@v9.0.31
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Store new tag as output
        id: get-tag
        run: echo "::set-output name=tag::$( git tag --points-at HEAD )"

  release-publish:
    runs-on: ubuntu-latest
    needs: version-bump
    if: ${{ success() && needs.version-bump.outputs.tag != '' }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: build
        run: |
          npm ci
          npm run build
          rm node_modules -rf
          npm ci --exclude=dev
          npm pack
      - uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: ${{ needs.version-bump.outputs.tag }}
          files: dsyn-cli-*.tgz
      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
