name: PR

on:
  pull_request_target:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/verify
        with:
          ref: ${{ github.head_ref }}
